### ISSUE TITLE
config.xml not loading from correct folder. (2009021)

### ISSUE THREAD

**Issue by dbrgss** [blackberry/Ripple-Framework#24]
Revision: e04350f545b6c4ae8b8a9203418b461cf19160c9
origin/omnibar

Starbuck always try to load config.xml from UI location folder , but not from webworks application folder .

1) when start Starbuck , web inspector shows XHR loadinf config.xml from UI location folder

2) when switch to a webworks application in omni bar , web inspector does not show any loading action for config.xml

when  make a  XHR  call ,  it always looking  under  UI path  but not  under webworks application path .

**Comment by ghost** [comment]
Dave, do you have a webwork app example for this

**Comment by ghost** [comment]
Reason: 
1) Only file name ( config.xml ) not the full path was passed to js XMLHttpRequest.open() at the UI load stage.
   XHR call was triggered within ripple.js, which is executed when UI page is loaded. The UI location is the default location. 
   Full path is needed to fetch any resources which are not located in the UI location, for example,
   "http://localhost/mywebworkapp1/config.xml" instead of "config.xml"

2) When switch to a webworks application in omni bar, the native XMLHttpRequest.open() was not called to retrieve config.xml for this application

Solution: We need to resolve No. 2 from java script side first, i.e. config.xml must be retrieved when starting a webworks application.

**Comment by kwallis** [comment]
Fixed
